version: "3.0"

services:
  nginx:
    image: nto-nginx
    container_name: nto-nginx
    restart: unless-stopped
    # volumes:
    #   - ./templates:/etc/nginx/templates
    ports:
      - ${FRONTEND_PORT}:10100
      - ${PGADMIN_PORT}:10102
      - ${USERS_SERVICE_PORT}:10102
      - ${BACKEND_SERVICE_PORT}:10102
    networks:
      - postgres
      - front

networks:
  postgres:
    external: true
  front:
    external: true
