services:
  web:
    image: nto-nginx
    # volumes:
    #   - ./templates:/etc/nginx/templates
    ports:
      - ${PGADMIN_PORT}:10100
      - ${PORTAINER_PORT}:20001
    networks:
      - postgres

networks:
  postgres:
    external: true